# Generated by Django 4.2.11 on 2024-03-18 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comments', models.IntegerField(default=0)),
                ('badge_text', models.CharField(max_length=50)),
                ('badge_color', models.CharField(max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('attachments', models.IntegerField(default=0)),
                ('assigned', models.ManyToManyField(related_name='assigned_items', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kanban.board')),
                ('members', models.ManyToManyField(related_name='member_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
